### PR TITLE
Qrcode lib

### PR DESCRIPTION
**Pull request by dodgymike**
Hi,

The first of a few pull requests I'll submit this weekend :)

This one uses rqrcode_png to generate the qrcode image.

Thanks,
Mike

### CODE REVIEW

**Comment by wmlele** [comment]
Not sure if you noticed, there's a qrcode branch that's producing the qrcode on the client using qrcode.js. Admittedly it is a bit lagging behind, but it's a single commit.

**Comment by wmlele** [comment]
Glad someone helps maintaining this project :)

**Comment by dodgymike** [comment]
Probably better to generate on the client ... any chance you're going to merge it soon?

**Comment by dodgymike** [comment]
Perfect gem for my latest rails project :+1:

**Comment by wmlele** [comment]
I am merging it tomorrow.

**Comment by dodgymike** [comment]
Great, thanks :)

**Pull request closed without merging**
