### PR TITLE
CHANGED: Update supported Rails version to v7.2

### PR DESCRIPTION
**Pull request by tarellel**
**Summary:**

Update the support Rails version to v7.2.

When testing the gem with Rails v7.2 I didn't come across any issues and the functionality seemed to appear as intended. But that doesn't mean all use cases were covered.

**Screenshots:**

When attempting to upgrade a Rails v7.1 application to v7.2 while using the devise-otp gem.

Screenshot 2024-08-10 at 12 11 01 AM

**Additional follow-up issue**

- >`Remove deprecated support to passing `SchemaMigration` and `InternalMetadata` classes as arguments to
    `ActiveRecord::MigrationContext`.`

https://github.com/rails/rails/blob/c44d7ae6b1e0292a95a27b7a5573f4dec99e06f0/guides/source/7_2_release_notes.md?plain=1#L438

### CODE REVIEW

**Comment by strzibny** [comment]
Sure, let's run the test suite and merge.

**Comment by n-rodriguez** [comment]
ping @strzibny

**Comment by strzibny** [comment]
@n-rodriguez The test suite was run but needs a fix. I don't see any new change.

**Comment by tarellel** [comment]
@strzibny 
All tests are passing locally, please try again on the CI.

**Pull request merged**
