### PR TITLE
Sprockets fix

### PR DESCRIPTION
**Pull request by n-rodriguez**
Thank you!

### CODE REVIEW

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by strzibny** [comment]
@n-rodriguez completely missed this PR. Sorry about that. Would be so kind and update it to latest changes? I was changing the paths so they are configurable and match Devise by default.

**Comment by strzibny** [comment]
If you have some time I'll be fast to review and merge, if not I'll pick up on these changes and include them myself.

**Comment by n-rodriguez** [comment]
> Would be so kind and update it to latest changes? I was changing the paths so they are configurable and match Devise by default.

rebase done! thank you!

**Comment by n-rodriguez** [comment]
CI result: https://github.com/n-rodriguez/devise-otp/actions/runs/1973388434

**Pull request merged**
