### PR TITLE
Generare QR Codes as SVG

### PR DESCRIPTION
**Pull request by strouptl**
Description: This Pull Request updates devise otp to generate QR Codes as SVGs via the rqrcode gem. This eliminates any JavaScript or Sprockets dependencies in preparation for importmaps (now the only option for new apps in Rails 8).

Changes:
- Add rqrcode to Gemspec
- Update otp_authenticator_token_image helper method to generate QR Code direclty as SVG
- Remove other QR Code generation methods
- Remove references to QRCode.js
- Remove devise-otp.js and assets/javascripts directory (no longer needed)
- Update README

### CODE REVIEW

**Comment by strouptl** [comment]
Resolves Issue #93

**Comment by strouptl** [comment]
Rebased.

**Comment by strouptl** [comment]
Note that we would need to direct existing users in the Changelog to remove devise-otp.js from their JavaScript, and add devise-otp.css to their CSS;

**Comment by strouptl** [comment]
FYI, DHH has announced that no new Rails projects should be started with Sprockets. So, I think we are making this change just in time.

https://github.com/rails/rails/pull/52887

**Comment by strzibny** [comment]
It works well for me, thanks, and sorry about the delay.

**Pull request merged**
