### PR TITLE
Utilize Warden Redirect

### PR DESCRIPTION
**Pull request by strouptl**
This PR utilizes the native Warden "redirect!" method to redirect users from the sign in form to the OTP challenge without signing in. Benefits of this approach include:

- Eliminates artifical login/logout in the "create\_otp\_session" method;
- Avoides destroying the Warden session (which eliminates the need for getting/resetting the redirect location);
- Ensures that trackakable fields are only updated after entering OTP credentials;
- Removes the Sessions hook in general in conjunction with PR's #78, and #79

NOTE: tests are failing, as the above PR's must be merged first.

### CODE REVIEW

**Comment by strzibny** [comment]
Please rebase

**Comment by strouptl** [comment]
Hi @strzibny, the tests on this branch are still failing for some reason. I will let you know when I get them resolved.

**Comment by strouptl** [comment]
@strzibny, I have a solution for this in PR #82. If you could merge PR's #81 and #82 first, then I will rebase and merge this final PR to closeout the Trackable field issues in Issue 71.

**Comment by strzibny** [comment]
Okay, please rebase to master. I'll do more testing of this after. After that I could cut a new release with the changes.

**Comment by strouptl** [comment]
OK, I have rebased. It is ready for you.

**Comment by strzibny** [comment]
Please rebase again

**Comment by strouptl** [comment]
Done.

**Pull request merged**
